// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvzSmDVLKNUxNaS-ia8YvU4m3TXFVf-ZE',
    appId: '1:611359423677:web:e16824168b1803b2afcbd4',
    messagingSenderId: '611359423677',
    projectId: 'ayuthaya-camp',
    authDomain: 'ayuthaya-camp.firebaseapp.com',
    storageBucket: 'ayuthaya-camp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlLsSxyjTvm0lNUOQHZIVfCvZqjz6owgw',
    appId: '1:611359423677:android:b00380b52f4c2a0fafcbd4',
    messagingSenderId: '611359423677',
    projectId: 'ayuthaya-camp',
    storageBucket: 'ayuthaya-camp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmB-07NDhXla9Ll6qf7QTSVi7IDXQzm-Y',
    appId: '1:611359423677:ios:2c3bff64909754f7afcbd4',
    messagingSenderId: '611359423677',
    projectId: 'ayuthaya-camp',
    storageBucket: 'ayuthaya-camp.firebasestorage.app',
    iosClientId: '611359423677-gf9bcst1m6qsdmqbukajfblkc6l4982p.apps.googleusercontent.com',
    iosBundleId: 'com.ayutthaya.ayutthayaCamp',
  );
}
